/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

public class App {
	public String getGreeting() {
		return "Hello World!";
	}

	public static void main(String[] args) {
		System.out.println(new App().getGreeting());
	}


	public boolean containsDuplicate(int[] nums) {
		return false;
	}

}
